version: "3.8"

services:
  postgres-auth:
    image: postgres:15
    container_name: auth-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "50051:50051"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      USER_SERVICE_URL: user-service:50052
    depends_on:
      postgres-auth:
        condition: service_healthy
      user-service:
        condition: service_started
    restart: unless-stopped

  postgres-user:
    image: postgres:15
    container_name: user-postgres
    environment:
      POSTGRES_USER: useruser
      POSTGRES_PASSWORD: userpass
      POSTGRES_DB: userdb
    ports:
      - "5433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U useruser -d userdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: user-service
    ports:
      - "50052:50052"
    environment:
      DATABASE_URL: postgres://useruser:userpass@postgres-user:5432/userdb?sslmode=disable
    depends_on:
      postgres-user:
        condition: service_healthy
    restart: unless-stopped

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      AUTH_SERVICE_URL: auth-service:50051
      USER_SERVICE_URL: user-service:50052
      PORT: "8080"
    depends_on:
      - auth-service
      - user-service
    restart: unless-stopped

volumes:
  auth-db-data:
  user-db-data:
